name: Docker_Image_CI

env:
  APP : "api-${{ github.sha }}" 

on:
  push:
    branches: 
      - main


jobs:
  create:
    runs-on: self-hosted


    steps:
    - name: create jobs world
      run : |
        ls
        apt install git-all -y
        git clone ${{github.repositoryUrl}} .
        ls
  build:
    runs-on: ubuntu-latest
    needs: [create]

    steps:
    - name: Print Hello world
      run : echo hello world