name: Docker_Image_CI

env:
  APP : "api-${{ github.sha }}" 

on:
  push:
    branches: 
      - main


jobs:
  create:
    runs-on: self-hosted
    steps:
    - name: create jobs world
      uses: actions/checkout@v3
    - name: ls 
      run : |
        echo "${{ secrets.CONNECT_COMMAND }}"
        echo "${{secrets.CONNECT_TOKEN}}"
        ls
  build:
    runs-on: ubuntu-latest
    needs: [create]

    steps:
    - name: Print Hello world
      run : echo hello world